// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Urr_P2YWcGio7tKuzxy48_XYrsigmgg',
    appId: '1:399528666814:web:b35e2c51cd8fb61dd3e0ef',
    messagingSenderId: '399528666814',
    projectId: 'mitishamba-758db',
    authDomain: 'mitishamba-758db.firebaseapp.com',
    storageBucket: 'mitishamba-758db.firebasestorage.app',
    measurementId: 'G-Z0GEP5K3D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5jG8lI07FfQVjO9INpPPdViDs7NJ59hE',
    appId: '1:399528666814:android:a2863638e092a09cd3e0ef',
    messagingSenderId: '399528666814',
    projectId: 'mitishamba-758db',
    storageBucket: 'mitishamba-758db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnMfo_Hgz_ezyPdB1eP5DpSBtsVl61qgo',
    appId: '1:399528666814:ios:016e878edab5d0e1d3e0ef',
    messagingSenderId: '399528666814',
    projectId: 'mitishamba-758db',
    storageBucket: 'mitishamba-758db.firebasestorage.app',
    iosBundleId: 'com.example.mitidawa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnMfo_Hgz_ezyPdB1eP5DpSBtsVl61qgo',
    appId: '1:399528666814:ios:016e878edab5d0e1d3e0ef',
    messagingSenderId: '399528666814',
    projectId: 'mitishamba-758db',
    storageBucket: 'mitishamba-758db.firebasestorage.app',
    iosBundleId: 'com.example.mitidawa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Urr_P2YWcGio7tKuzxy48_XYrsigmgg',
    appId: '1:399528666814:web:5458db4cadf39a5fd3e0ef',
    messagingSenderId: '399528666814',
    projectId: 'mitishamba-758db',
    authDomain: 'mitishamba-758db.firebaseapp.com',
    storageBucket: 'mitishamba-758db.firebasestorage.app',
    measurementId: 'G-YNBQMKZ7TD',
  );
}
